services:
  # =========================
  # Backend (Docker)
  # =========================
  - type: web
    runtime: docker
    name: backend
    dockerfilePath: app/backend/Dockerfile
    plan: free
    autoDeployTrigger: commit
    healthCheckPath: /healthz
    envVars:
      - key: PORT
        value: "8080"
      # DB接続例（pserv名= mysql を内部ホストとして使える）
      - key: DB_HOST
        value: mysql
      - key: DB_PORT
        value: "3306"
      - key: DB_USER
        value: app
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: appdb

  # =========================
  # Frontend (Static Site)
  # =========================
  - type: web          # ← static ではなく web
    runtime: static    # ← 静的サイトは runtime: static
    name: frontend
    buildCommand: |
      cd app/frontend
      npm ci
      npm run build
    staticPublishPath: app/frontend/dist
    plan: free
    autoDeployTrigger: commit
    routes:
      - type: rewrite
        source: /**/*
        destination: /index.html
    envVars:
      - key: VITE_API_BASE_URL
        value: https://backend.onrender.com   # ← 初回後に実URLへ差し替え

  # =========================
  # MySQL (Private Service)  ← ここが修正ポイント
  # =========================
  - type: pserv        # ← private ではなく pserv
    runtime: docker
    name: mysql
    image: docker.io/mysql:8.4
    plan: starter
    autoDeployTrigger: commit
    envVars:
      - key: MYSQL_DATABASE
        value: appdb
      - key: MYSQL_USER
        value: app
      - key: MYSQL_PASSWORD
        generateValue: true
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
    disk:
      name: mysqldata
      mountPath: /var/lib/mysql
      sizeGB: 10