services:
  # =========================
  # Backend (Go + Docker)
  # =========================
  - type: web
    name: backend
    runtime: docker
    dockerfilePath: app/backend/Dockerfile
    # 任意: リポジトリ直下が root。サブディレクトリでビルド文脈を変えたい場合は rootDir も検討
    # rootDir: app/backend
    plan: free
    healthCheckPath: /healthz
    envVars:
      - key: PORT
        value: "8080"
      # DB を使うなら（下の mysql サービスと合わせる）
      - key: DB_HOST
        value: mysql
      - key: DB_PORT
        value: "3306"
      - key: DB_USER
        value: app
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: appdb

  # =========================
  # Frontend (Vite を Static Site としてCDN配信)
  # =========================
  - type: web
    name: frontend
    runtime: static
    buildCommand: |
      cd app/frontend
      npm ci
      npm run build
    staticPublishPath: app/frontend/dist
    plan: free
    routes:
      - type: rewrite
        source: /**/*
        destination: /index.html
    envVars:
      - key: VITE_API_BASE_URL
        value: https://backend.onrender.com  # 初回デプロイ後に実URLへ更新

  # =========================
  # (任意) MySQL as Private Service
  # =========================
  - type: pserv          # ← private ではなく pserv
    name: mysql
    runtime: docker
    image: docker.io/mysql:8.4
    plan: starter        # ← private service は free プラン不可
    envVars:
      - key: MYSQL_DATABASE
        value: appdb
      - key: MYSQL_USER
        value: app
      - key: MYSQL_PASSWORD
        generateValue: true
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
      - key: PORT
        value: "3306"
    disk:
      name: mysqldata
      mountPath: /var/lib/mysql
      sizeGB: 10