services:
  # =========================
  # Backend (Go + Docker)
  # =========================
  - type: web
    name: backend
    runtime: docker
    dockerfilePath: app/backend/Dockerfile
    plan: free
    healthCheckPath: /healthz
    envVars:
      - key: PORT
        value: "8080"
      # （DBを使う場合の例）
      - key: DB_HOST
        value: mysql
      - key: DB_PORT
        value: "3306"
      - key: DB_USER
        value: app
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: appdb

  # =========================
  # Frontend
  # =========================
  - type: web
    name: frontend
    runtime: static
    buildCommand: |
      cd app/frontend
      npm ci
      npm run build
    staticPublishPath: app/frontend/dist
    plan: free
    routes:
      - type: rewrite
        source: /**/*
        destination: /index.html   # SPA ルーティング
    envVars:
      - key: VITE_API_BASE_URL
        value: https://backend.onrender.com  # 初回後、実URLに更新

  # =========================
  # MySQL を内部サービスで動かす
  # =========================
  - type: pserv
    name: mysql
    runtime: docker
    image: docker.io/mysql:8.4
    plan: starter
    envVars:
      - key: MYSQL_DATABASE
        value: appdb
      - key: MYSQL_USER
        value: app
      - key: MYSQL_PASSWORD
        generateValue: true
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
      - key: PORT
        value: "3306"
    disk:
      name: mysqldata
      mountPath: /var/lib/mysql
      sizeGB: 10