services:
  - type: web
    name: backend
    runtime: docker
    dockerfilePath: app/backend/Dockerfile
    dockerContext: app/backend
    plan: free
    # 必要に応じて追加: healthCheckPath: /healthz
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: appdb
          property: host
      - key: DB_PORT
        fromDatabase:
          name: appdb
          property: port
      - key: DB_USER
        fromDatabase:
          name: appdb
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: appdb
          property: password
      - key: DB_NAME
        fromDatabase:
          name: appdb
          property: database

  - type: web
    name: frontend
    runtime: static
    buildCommand: |
      cd app/frontend
      npm ci
      npm run build
    staticPublishPath: app/frontend/dist
    routes:
      - type: rewrite
        source: /**/*
        destination: /index.html
    envVars:
      - key: VITE_API_BASE_URL
        value: https://backend.onrender.com

databases:
  - name: appdb
    plan: free
    databaseName: appdb
    user: app
