services:
  # ================
  # Backend (Go + Docker)
  # ================
  - type: web
    name: backend
    runtime: docker
    dockerfilePath: app/backend/Dockerfile
    plan: free
    healthCheckPath: /healthz
    autoDeploy: true
    envVars:
      - key: PORT
        value: "8080"
      # DBを使うなら以下
      - key: DB_HOST
        value: mysql
      - key: DB_PORT
        value: "3306"
      - key: DB_USER
        value: app
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: appdb

  # ================
  # Frontend (Vite → Static)
  # ================
  - type: web
    name: frontend
    runtime: static
    plan: free
    autoDeploy: true
    buildCommand: |
      cd app/frontend
      npm ci
      npm run build
    staticPublishPath: app/frontend/dist
    routes:
      - type: rewrite
        source: /**/*
        destination: /index.html
    envVars:
      - key: VITE_API_BASE_URL
        value: https://backend.onrender.com  # デプロイ後に実URLへ更新

  # ================
  # MySQL (Private Service)
  # ================
  - type: pserv
    name: mysql
    runtime: docker
    plan: starter
    autoDeploy: true
    image:
      url: docker.io/mysql:8.4   # ← 文字列ではなくオブジェクトで指定
    envVars:
      - key: MYSQL_DATABASE
        value: appdb
      - key: MYSQL_USER
        value: app
      - key: MYSQL_PASSWORD
        generateValue: true
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
      - key: PORT
        value: "3306"
    disk:
      name: mysqldata
      mountPath: /var/lib/mysql
      sizeGB: 10