services:
  # ================
  # Backend (Go + Docker)
  # ================
  - type: web
    name: backend
    runtime: docker
    dockerfilePath: app/backend/Dockerfile
    plan: free
    healthCheckPath: /healthz
    autoDeployTrigger: commit
    envVars:
      - key: PORT
        value: "8080"
      # DBを使うなら以下追加
      - key: DB_HOST
        value: mysql
      - key: DB_PORT
        value: "3306"
      - key: DB_USER
        value: app
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: appdb

  # ================
  # Frontend (Static site via Vite build)
  # ================
  - type: web
    name: frontend
    runtime: static
    plan: free
    autoDeployTrigger: commit
    buildCommand: |
      cd app/frontend
      npm ci
      npm run build
    staticPublishPath: app/frontend/dist
    routes:
      - type: rewrite
        source: /**/*
        destination: /index.html
    envVars:
      - key: VITE_API_BASE_URL
        value: https://backend.onrender.com  # ← デプロイ後に backend 実URLに書き換え

  # ================
  # (任意) MySQL as internal service
  # ================
  - type: pserv
    name: mysql
    runtime: docker
    plan: starter
    autoDeployTrigger: commit
    image: docker.io/mysql:8.4
    envVars:
      - key: MYSQL_DATABASE
        value: appdb
      - key: MYSQL_USER
        value: app
      - key: MYSQL_PASSWORD
        generateValue: true
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
      - key: PORT
        value: "3306"
    disk:
      name: mysqldata
      mountPath: /var/lib/mysql
      sizeGB: 10