services:
  # =========================
  # Go Backend (Docker)
  # =========================
  - type: web
    name: backend
    env: docker
    dockerfilePath: app/backend/Dockerfile
    autoDeploy: true
    plan: free
    # アプリ側で PORT を参照して Listen してください（Render が付与）
    # 例) :os.Getenv("PORT") / default 8080
    healthCheckPath: /healthz
    envVars:
      - key: APP_ENV
        value: production
      # フロントの CORS を許可（必要に応じて後で置き換え）
      - key: CORS_ORIGINS
        value: "*"
      # ==== DB を使う場合 ====
      - key: DB_HOST
        value: mysql
      - key: DB_PORT
        value: "3306"
      - key: DB_USER
        value: app
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: appdb

    # DB（private service）へは内部ホスト名で到達
    # backend → mysql へは `mysql:3306` で接続できます
    dependsOn:
      - name: mysql
        required: false

  # =========================
  # Static Frontend (Vite build)
  # =========================
  - type: web
    runtime: static
    name: frontend
    buildCommand: |
      cd app/frontend
      npm ci
      npm run build
    staticPublishPath: app/frontend/dist
    autoDeploy: true
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=600
    # 任意: SPA ルーティング（/xxx を /index.html にフォールバック）
    routes:
      - type: rewrite
        source: /**/*
        destination: /index.html
    envVars:
      # ここに “backend” の公開URL を設定（デプロイ後に置換でもOK）
      - key: VITE_API_BASE_URL
        value: https://backend.onrender.com

  # =========================
  # (任意) MySQL as Private Service
  # Render の “Disk” を付けて永続化
  # =========================
  - type: private
    name: mysql
    env: docker
    plan: starter
    autoDeploy: true
    # 公式イメージを利用（compose を使わず Blueprint で完結）
    image: docker.io/mysql:8.4
    envVars:
      - key: MYSQL_DATABASE
        value: appdb
      - key: MYSQL_USER
        value: app
      - key: MYSQL_PASSWORD
        generateValue: true
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
    disk:
      name: mysqldata
      mountPath: /var/lib/mysql
      sizeGB: 10