services:
  app-backend:
    build:
      context: ../app/backend
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env
    environment:
      - PORT=${BACKEND_PORT}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - APP_ENV=${APP_ENV}
    ports:
      - "${BACKEND_PORT}:8080"
    volumes:
      - ../app/backend:/app
      - go_pkg:/go/pkg/mod
      - go_build:/root/.cache/go-build
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:8080/health"]
      interval: 5s
      timeout: 3s
      retries: 10

  app-frontend:
    build:
      context: ../app/frontend
      target: dev
    env_file:
      - ./.env
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    ports:
      - "${FRONTEND_PORT}:5173"
    volumes:
      - ../app/frontend:/app
      - frontend_node_modules:/app/node_modules
    depends_on:
      app-backend:
        condition: service_started

volumes:
  go_pkg: {}
  go_build: {}
  frontend_node_modules: {}
